// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: pkg/rpc/proto/generic_rpc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenericRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	Server        string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Body          string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericRequest) Reset() {
	*x = GenericRequest{}
	mi := &file_pkg_rpc_proto_generic_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericRequest) ProtoMessage() {}

func (x *GenericRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_generic_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericRequest.ProtoReflect.Descriptor instead.
func (*GenericRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_generic_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GenericRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GenericRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *GenericRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *GenericRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *GenericRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	NodeIp        string                 `protobuf:"bytes,2,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`
	Ts            int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_pkg_rpc_proto_generic_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_proto_generic_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_proto_generic_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *GenericResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GenericResponse) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

func (x *GenericResponse) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *GenericResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GenericResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GenericResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_rpc_proto_generic_rpc_proto protoreflect.FileDescriptor

const file_pkg_rpc_proto_generic_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/rpc/proto/generic_rpc.proto\x12\vgeneric_rpc\"\x85\x01\n" +
	"\x0eGenericRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\"\x94\x01\n" +
	"\x0fGenericResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x17\n" +
	"\anode_ip\x18\x02 \x01(\tR\x06nodeIp\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage2\xa3\x01\n" +
	"\x0eGenericService\x12G\n" +
	"\bExchange\x12\x1b.generic_rpc.GenericRequest\x1a\x1c.generic_rpc.GenericResponse\"\x00\x12H\n" +
	"\tHeartbeat\x12\x1b.generic_rpc.GenericRequest\x1a\x1c.generic_rpc.GenericResponse\"\x00B\x1bZ\x19mcp-gateway/pkg/rpc/protob\x06proto3"

var (
	file_pkg_rpc_proto_generic_rpc_proto_rawDescOnce sync.Once
	file_pkg_rpc_proto_generic_rpc_proto_rawDescData []byte
)

func file_pkg_rpc_proto_generic_rpc_proto_rawDescGZIP() []byte {
	file_pkg_rpc_proto_generic_rpc_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_proto_generic_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_proto_generic_rpc_proto_rawDesc), len(file_pkg_rpc_proto_generic_rpc_proto_rawDesc)))
	})
	return file_pkg_rpc_proto_generic_rpc_proto_rawDescData
}

var file_pkg_rpc_proto_generic_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_rpc_proto_generic_rpc_proto_goTypes = []any{
	(*GenericRequest)(nil),  // 0: generic_rpc.GenericRequest
	(*GenericResponse)(nil), // 1: generic_rpc.GenericResponse
}
var file_pkg_rpc_proto_generic_rpc_proto_depIdxs = []int32{
	0, // 0: generic_rpc.GenericService.Exchange:input_type -> generic_rpc.GenericRequest
	0, // 1: generic_rpc.GenericService.Heartbeat:input_type -> generic_rpc.GenericRequest
	1, // 2: generic_rpc.GenericService.Exchange:output_type -> generic_rpc.GenericResponse
	1, // 3: generic_rpc.GenericService.Heartbeat:output_type -> generic_rpc.GenericResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_rpc_proto_generic_rpc_proto_init() }
func file_pkg_rpc_proto_generic_rpc_proto_init() {
	if File_pkg_rpc_proto_generic_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_proto_generic_rpc_proto_rawDesc), len(file_pkg_rpc_proto_generic_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_proto_generic_rpc_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_proto_generic_rpc_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_proto_generic_rpc_proto_msgTypes,
	}.Build()
	File_pkg_rpc_proto_generic_rpc_proto = out.File
	file_pkg_rpc_proto_generic_rpc_proto_goTypes = nil
	file_pkg_rpc_proto_generic_rpc_proto_depIdxs = nil
}
